version: 2.1

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      - image: node:22-alpine

    steps:
      - checkout

      - run:
          name: Install stuff
          command: "apk add wget curl"

      - run:
          name: Install dependencies
          command: "node --version && npm install"

      # - run:
      #     name: Install LocalTunnel globally
      #     command: "npm install -g localtunnel"

      - run:
          name: Find IP
          command: "curl https://loca.lt/mytunnelpassword"

      # - run:
      #     name: Get IP - alternative
      #     command: |
      #       echo $'GET /mytunnelpassword HTTP/1.1\r\nHost: loca.lt\r\nConnection: close\r\n\r\n' | \
      #       openssl s_client -connect loca.lt:443 2>/dev/null | sed -n '/^\r$/,$p' | tail -n +2

      - run:
          name: Run application
          command: "nohup npm start > app.log 2>&1 &"

      - run:
        name: Look at app
        command: for i in {1..10}; do curl localhost:8000 && break || sleep 3; done

      - run:
          name: Install Cloudflared
          command: "wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared"

      - run:
          name: Run Cloudflare Tunnel
          command: "./cloudflared --url http://localhost:8000 --no-tls-verify"
      - run:
          name: Localtunnel
          command: "npm install -g localtunnel && lt -p 8000 -s doge"
