version: 2.1

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install Node.js
          command: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && . ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts"

      - run:
          name: Install dependencies
          command: "node --version && nvm install 22 && nvm use 22 && npm install"

      # - run:
      #     name: Install LocalTunnel globally
      #     command: "npm install -g localtunnel"

      - run:
          name: Find IP
          command: "curl https://loca.lt/mytunnelpassword"

      # - run:
      #     name: Get IP - alternative
      #     command: |
      #       echo $'GET /mytunnelpassword HTTP/1.1\r\nHost: loca.lt\r\nConnection: close\r\n\r\n' | \
      #       openssl s_client -connect loca.lt:443 2>/dev/null | sed -n '/^\r$/,$p' | tail -n +2

      - run:
          name: Run application
          command: "npm start"

      # - run:
      #     name: Test application
      #     command: "curl http://localhost:8000"

      - run:
          name: Install Cloudflared
          command: "wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared"

      - run:
          name: Run Cloudflare Tunnel
          command: "./cloudflared --url http://localhost:8000"
