name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: install node and npm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: npm
        run: |
          "npm i"
          "npm start &"
      - name: use cloudflare
        run: |
          "wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared"
          "./cloudflared --url http://localhost:8000"
