name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm i"

      - name: Build step
        run: "npm install -g localtunnel"

      - name: Find ip
        run: "curl https://loca.lt/mytunnelpassword"
        
#      - name: get ip
#        run: "python3 -c \"import requests; print(requests.get('https://loca.lt/mytunnelpassword').text)\""

      - name: get ip part 2
        run: "echo $'GET /mytunnelpassword HTTP/1.1\r\nHost: loca.lt\r\nConnection: close\r\n\r\n' | openssl s_client -connect loca.lt:443 2>/dev/null | sed -n '/^\r$/,$p' | tail -n +2"

      - name: run
        run: "npm start &"
        
      - name: cloudflare
        run: "wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared"
      
      - name: run cloudfare
        run: "./cloudflared --url https://localhost:8000 --no-tls-verify"
#      - name: Test localtunnel
#        run: "lt -p 8000 -s wy-doge"

          
