name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Stuff
        run: "npm i"

      - name: run
        run: "npm start &"

      - name: test
        run: "curl http://localhost:8000"
        
      - name: downlaod cloudflare
        run: "wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared"
      
      - name: run cloudfare
        run: "./cloudflared --url http://localhost:8000"
